// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coguyaxzvbakmypoxiuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZ3V5YXh6dmJha215cG94aXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDMzNzAsImV4cCI6MjA3MzAxOTM3MH0.VaxujXrL4Kx7ggM5Dpyxvt5LZ79nOXaCqft3GFChfHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});